import { roles } from "./roles";

// NOTE: this matrix is a local legacy mapping only. Real permissions and roles come from
// the backend user payload and should be checked dynamically via the authenticated user.
export const permissionMatrix = {
  [roles.SUPER_ADMIN]: ["*"],
  [roles.ADMIN]: [
    "LEADS_VIEW",
    "LEADS_CREATE",
    "LEADS_EDIT",
    "LEADS_DELETE",
    "LEADS_CONVERT",
    "CLIENTS_VIEW",
    "CLIENTS_CREATE",
    "CLIENTS_EDIT",
    "CLIENTS_DELETE",
    "PROJECTS_VIEW",
    "PROJECTS_CREATE",
    "PROJECTS_EDIT",
    "PROJECTS_DELETE",
    "INVOICES_VIEW",
    "INVOICES_CREATE",
    "INVOICES_EDIT",
    "INVOICES_DELETE",
    "CONTRACTS_VIEW",
    "CONTRACTS_CREATE",
    "CONTRACTS_EDIT",
    "CONTRACTS_DELETE",
    "TICKETS_VIEW",
    "TICKETS_CREATE",
    "TICKETS_EDIT",
    "TICKETS_DELETE",
    "ASSETS_VIEW",
    "ASSETS_CREATE",
    "ASSETS_EDIT",
    "ASSETS_DELETE",
    "REPORTS_VIEW",
    "SETTINGS_VIEW",
  ],
  [roles.MANAGER]: [
    "LEADS_VIEW",
    "LEADS_CREATE",
    "LEADS_EDIT",
    "LEADS_CONVERT",
    "CLIENTS_VIEW",
    "PROJECTS_VIEW",
    "INVOICES_VIEW",
    "TICKETS_VIEW",
    "REPORTS_VIEW",
  ],
  [roles.EMPLOYEE]: [
    "LEADS_VIEW",
    "CLIENTS_VIEW",
    "PROJECTS_VIEW",
    "TICKETS_VIEW",
  ],
} as const;
